### ISSUE TITLE
Support Unreal version 5.4 (Shipping + DebugGame configs)

### ISSUE THREAD

**Issue by infinstarlight** [JonasReich/OpenUnrealUtilities#7]
Hi there, I am attempting to build my project under the Shipping config using the latest version of the plugin (v1.3.0). The build failed and the AutomationTool provided this from the log 

`C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUDeveloper\Public\OUUMapsToCookSettings.h(18): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUDeveloper\Public\OUUMapsToCookSettings.h(21): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\OUUEditorLibrary.h(17): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\OUUEditorLibrary.h(21): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\OUUEditorLibrary.h(25): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(18): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(21): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(36): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(41): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(44): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(48): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(53): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(56): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(60): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(65): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(82): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(86): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUEditor\Public\GameplayTagValidator.h(113): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\ExclusiveLock.h(28): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(18): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(21): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(24): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(27): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(30): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\ExclusiveLock.h(37): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(33): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(36): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(39): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(42): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Logging\MessageLogToken.h(127): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(45): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
Total of 0 written
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\ExclusiveLock.h(44): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUUMG\Public\Window\OUUWindowParameters.h(48): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Logging\MessageLogToken.h(130): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Logging\MessageLogToken.h(133): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Logging\MessageLogToken.h(136): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\ExclusiveLock.h(48): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Logging\MessageLogToken.h(139): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequest.h(71): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequest.h(75): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequest.h(79): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequest.h(86): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequest.h(93): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequest.h(97): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequest.h(104): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Math\SpiralIdUtilities.h(87): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Math\SpiralIdUtilities.h(95): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Math\SpiralIdUtilities.h(105): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequestQueue.h(32): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Math\SpiralIdUtilities.h(119): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequestQueue.h(41): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequestQueue.h(50): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Math\SpiralIdUtilities.h(129): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequestQueue.h(60): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Math\SpiralIdUtilities.h(141): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequestQueue.h(68): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\OUURequestQueue.h(82): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Math\SpiralIdUtilities.h(156): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Math\SpiralIdUtilities.h(175): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\SharedLock.h(30): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Misc\RegexUtils.h(25): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Misc\RegexUtils.h(28): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Misc\RegexUtils.h(31): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\Misc\RegexUtils.h(62): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\SharedLock.h(40): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\SharedLock.h(48): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\SharedLock.h(55): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\SharedLock.h(62): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\FlowControl\SharedLock.h(69): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\GameplayTagDependencies.h(50): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\GameplayTagDependencies.h(55): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\GameplayTagDependencies.h(58): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\GameplayTagDependencies.h(62): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\PreReleaseIdentifier.h(73): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\PreReleaseIdentifier.h(77): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\GameplayTagDependencies.h(65): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\SemanticVersion.h(60): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\GameplayTagDependencies.h(68): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\SemanticVersion.h(63): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\SemanticVersion.h(66): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\GameplayTagDependencies.h(71): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\SemanticVersion.h(69): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\SemanticVersion.h(72): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\OUUGameplayTagLibrary.h(17): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\OUUGameplayTagLibrary.h(20): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\OUUGameplayTagLibrary.h(23): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUBlueprintRuntime\Public\Core\OUUCoreBlueprintLibrary.h(53): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\OUUGameplayTagLibrary.h(26): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\OUUGameplayTagLibrary.h(29): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\OUUGameplayTagLibrary.h(32): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagContainer.h(69): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagContainer.h(78): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagContainer.h(94): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagContainer.h(99): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagContainer.h(102): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagContainer.h(107): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagContainer.h(112): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagContainer.h(117): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagSettings.h(19): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagSettings.h(24): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagSettings.h(30): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\GameplayTags\TypedGameplayTagSettings.h(92): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\BuildMetadata.h(49): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUURuntime\Public\SemVer\BuildMetadata.h(53): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUDeveloper\Public\OUUMapsToCookSettings.h(42): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUDeveloper\Public\OUUMapsToCookSettings.h(47): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUDeveloper\Public\OUUMapsToCookSettings.h(51): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
C:\ISS_COS\BuiltProjects\HostProject\Plugins\OpenUnrealUtilities\Source\OUUDeveloper\Public\OUUMapsToCookSettings.h(55): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
Total execution time: 6.19 seconds
Took 6.31s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\UE\5_4\Engine\Programs\AutomationTool\Saved\Logs\UBA-UnrealEditor-Win64-Development.txt)
AutomationException: UnrealBuildTool failed. See log for more details. (C:\UE\5_4\Engine\Programs\AutomationTool\Saved\Logs\UBA-UnrealEditor-Win64-Development.txt)
   at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, FileReference UnrealBuildToolDll, String CommandLine) in C:\UE\5_4\Engine\Source\Programs\AutomationTool\AutomationUtils\UBTUtils.cs:line 59
   at BuildPlugin.CompilePluginWithUBT(FileReference UnrealBuildToolDll, FileReference HostProjectFile, FileReference HostProjectPluginFile, PluginDescriptor Plugin, String TargetName, TargetType TargetType, UnrealTargetPlatform Platform, UnrealTargetConfiguration Configuration, List`1 ManifestFileNames, String InAdditionalArgs) in C:\UE\5_4\Engine\Source\Programs\AutomationTool\Scripts\BuildPluginCommand.Automation.cs:line 375
   at BuildPlugin.CompilePlugin(FileReference UnrealBuildToolDll, FileReference HostProjectFile, FileReference HostProjectPluginFile, PluginDescriptor Plugin, IReadOnlyList`1 HostPlatforms, List`1 TargetPlatforms, String AdditionalArgs) in C:\UE\5_4\Engine\Source\Programs\AutomationTool\Scripts\BuildPluginCommand.Automation.cs:line 265
   at BuildPlugin.ExecuteBuild() in C:\UE\5_4\Engine\Source\Programs\AutomationTool\Scripts\BuildPluginCommand.Automation.cs:line 140
   at AutomationTool.BuildCommand.Execute() in C:\UE\5_4\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 345
   at AutomationTool.BuildCommand.ExecuteAsync() in C:\UE\5_4\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 354
   at AutomationTool.Automation.ExecuteAsync(List`1 CommandsToExecute, Dictionary`2 Commands) in C:\UE\5_4\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 270
   at AutomationTool.Automation.ProcessAsync(ParsedCommandLine AutomationToolCommandLine, StartupTraceListener StartupListener, HashSet`1 ScriptModuleAssemblies) in C:\UE\5_4\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 164
AutomationTool executed for 0h 0m 7s
AutomationTool exiting with ExitCode=6 (6)`

If it is as simple as setting Category values for each of the properties then it should be a simple fix but I have not tried that yet.

**Comment by JonasReich** [comment]
Do I infer correctly from the source paths that you tried this with a rocket install of UE5.4?
Release 1.3 was checked to compile in Shipping Game and Development Editor configurations for UE 5.2 and 5.3, but 5.4 likely had breaking changes that didn't get adjusted for.

If you do make adjustments that make it compile fine for 5.4, I would be grateful for a pull request, so we can create a separate **ue5.4** branch.

**Comment by infinstarlight** [comment]
No, I was using a source build. I was using the RunUAT batch file to build the plugin in isolation from my project just to remove any other issues that may be present in the compilation process. 

I will make a fork of my changes when I get back to my desk. The only changes made were to assigning category specifiers to all of the UPROPERTY and UFUNCTION declarations. I tried to keep things as consistent with the original code as possible, but Rider's autofill may have taken some liberties as well.

**Comment by infinstarlight** [comment]
I also got this error related to the GetClassDefaultObject and GetClassDefaultObjectFromObject functions in the OUUCoreBlueprintLibrary when attempting to build for Windows and Linux with the DebugGame config

`------ Building 12 action(s) started ------
** For ProjectLion-Win64-DebugGame **
[1/12] Compile [x64] OUUCoreBlueprintLibrary.gen.cpp
C:\ISS_COS\ProjectLion\Intermediate\Build\Win64\ProjectLion\Inc\OUUBlueprintRuntime\UHT\OUUCoreBlueprintLibrary.gen.cpp(223): error C2079: 'Z_Construct_UFunction_UOUUCoreBlueprintLibrary_GetClassDefaultObject_Statics::OUUCoreBlueprintLibrary_eventGetClassDefaultObject_Parms::Class' uses undefined class 'TSubclassOf<UObject>'
C:\ISS_COS\ProjectLion\Intermediate\Build\Win64\ProjectLion\Inc\OUUBlueprintRuntime\UHT\OUUCoreBlueprintLibrary.gen.cpp(267): error C2664: 'UObject *UOUUCoreBlueprintLibrary::GetClassDefaultObject(TSubclassOf<UObject>)': cannot convert argument 1 from 'UClass *' to 'TSubclassOf<UObject>'
C:\ISS_COS\ProjectLion\Intermediate\Build\Win64\ProjectLion\Inc\OUUBlueprintRuntime\UHT\OUUCoreBlueprintLibrary.gen.cpp(267): note: use of undefined type 'TSubclassOf<UObject>'
C:\ISS_COS\ProjectLion\Plugins\OpenUnrealUtilities-1.3.0\Source\OUUBlueprintRuntime\Public\Core\OUUCoreBlueprintLibrary.h(23): note: see declaration of 'TSubclassOf<UObject>'
C:\ISS_COS\ProjectLion\Plugins\OpenUnrealUtilities-1.3.0\Source\OUUBlueprintRuntime\Public\Core\OUUCoreBlueprintLibrary.h(23): note: see declaration of 'UOUUCoreBlueprintLibrary::GetClassDefaultObject'
C:\ISS_COS\ProjectLion\Intermediate\Build\Win64\ProjectLion\Inc\OUUBlueprintRuntime\UHT\OUUCoreBlueprintLibrary.gen.cpp(267): note: while trying to match the argument list '(UClass *)'
** For ProjectLion-Linux-DebugGame **
[2/12] Compile OUUCoreBlueprintLibrary.gen.cpp
C:\ISS_COS\ProjectLion\Intermediate\Build\Linux\ProjectLion\Inc\OUUBlueprintRuntime\UHT\OUUCoreBlueprintLibrary.gen.cpp(223,24): error: implicit instantiation of undefined template 'TSubclassOf<UObject>'
                TSubclassOf<UObject> Class;
                                     ^
C:\UE\5_4\Engine\Source\Runtime\CoreUObject\Public\Templates\Casts.h(35,30): note: template is declared here
template<class TClass> class TSubclassOf;
                             ^
C:\ISS_COS\ProjectLion\Intermediate\Build\Linux\ProjectLion\Inc\OUUBlueprintRuntime\UHT\OUUCoreBlueprintLibrary.gen.cpp(267,78): error: implicit instantiation of undefined template 'TSubclassOf<UObject>'
        *(UObject**)Z_Param__Result=UOUUCoreBlueprintLibrary::GetClassDefaultObject(Z_Param_Class);
                                                                                    ^
C:\UE\5_4\Engine\Source\Runtime\CoreUObject\Public\Templates\Casts.h(35,30): note: template is declared here
template<class TClass> class TSubclassOf;
                             ^`

**Comment by JonasReich** [comment]
Thanks for the PR! I created a new ue5.4 branch based on your change and will check those other build configs you mentioned before the next release, which will then hopefully support UE 5.4 as well as 5.5

**Comment by JonasReich** [comment]
I'll keep this ticket open to track other minor changes required to support UE 5.4

**Comment by JonasReich** [comment]
Since this was opened, I added UE 5.4 to my list of engine versions to check during release testing - so the latest v1.4.0 release should build fine for Win64, Linux, and PS5.
